### ISSUE TITLE
Do your RecAdamOptimizer reproduce the paper result?

### ISSUE THREAD

**Issue by guotong1988** [timbereye/electra_squad#1]
@timbereye Thank you!

**Comment by timbereye** [comment]
我没有复现论文结果，但是我在squad2.0上做了实验，结果显示在大数据量下RecAdam效果不明显，小数据量下是有明显效果的。此外，该方法推广到一些业务数据上也取得了不错的效果。唯一不好的地方就是训练时会占用额外的显存（约增加一倍）。
